# Generated by Django 5.2.8 on 2025-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao_datasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=250)),
                ('doenca', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=100)),
                ('num_casos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'unique_together': {('municipio', 'doenca', 'periodo')},
            },
        ),
    ]
